### ISSUE TITLE
media-libs/vapoursynth-58 version bump

### ISSUE THREAD

**Issue by jeandestouches** [4re/vapoursynth-portage#110]
Hi,
R58 is out :https://github.com/vapoursynth/vapoursynth/releases/tag/R58
Possible to add it ? zimg would need a version bump as well (to 3.0.4) but it is not in gentoo tree yet.. so maybe in a few weeks.
Thanks.

**Comment by 4re** [comment]
Hi there,

For now, the overlay is updating to API3 compatible revisions of the ebuilds only. Some live-ebuilds already broke because of this and once I have the time I'm planning to update everything to Vapoursynth's API4 and forget about API3.

The reason I have not yet committed to this is in part because even being true that some plugins have gained a little bit of performance, with the new API, some others are, or were, way slower.

**Comment by jeandestouches** [comment]
I see. I'm only starting with vapoursynth so thanks for your comprehensive answer. Cheers :+1:

**Comment by TheGreatMcPain** [comment]
I started working on a pull-request yesterday which updates `vapoursynth` to R58, and moves previously bundled plugins (subtext, vivtc, removegrain, etc.) into their own seperate ebuilds.  Mainly because I was getting segfaults with the `vapoursynth-55` version of subtext.

Looks like R58 is still backwards compatible with API3 plugins, because FFMS 2.40 still compiles and runs fine.

**Comment by 4re** [comment]
I have most of the work already done, I was waiting for the time to test it and the plugins to catch up.

As I see interest in it, I will try to push it this week.

**Comment by 4re** [comment]
I guess it's fixed at e3e3309b4a48b848e3e12ed7cf39458a2324647e.
