### ISSUE TITLE
media-libs/vapoursynth-28-r1 and 9999 fails to build.

### ISSUE THREAD

**Issue by Moiman** [4re/vapoursynth-portage#20]
```
libtool: link: x86_64-pc-linux-gnu-gcc -shared  -fPIC -DPIC  src/filters/vivtc/.libs/libvivtc_la-vivtc.o   -Wl,--as-needed  -O3 -mfpmath=sse -msse2 -march=k8-sse3 -O2 -ggdb -Wl,-O1   -Wl,-soname -Wl,libvivtc.so -o .libs/libvivtc.so
libtool: link: ( cd ".libs" && rm -f "libvivtc.la" && ln -s "../libvivtc.la" "libvivtc.la" )
cython -o src/cython/vapoursynth.c /var/tmp/portage/media-libs/vapoursynth-28-r1/work/vapoursynth-28/src/cython/vapoursynth.pyx
[Errno 2] No such file or directory: '/var/tmp/portage/media-libs/vapoursynth-28-r1/work/vapoursynth-28_build/src/cython/vapoursynth.c'
Makefile:1906: recipe for target 'src/cython/vapoursynth.c' failed
make: *** [src/cython/vapoursynth.c] Error 1
 * ERROR: media-libs/vapoursynth-28-r1::vapoursynth failed (compile phase):
 *   emake failed
```

**Comment by 4re** [comment]
Please, upload the full build log somewhere and the output of `emerge --info`.

**Comment by Moiman** [comment]
https://bpaste.net/show/4e332e903669

**Comment by 4re** [comment]
This is kind of funny. So you are on a singl core cpu, right? The thing is if I set `MAKEOPTS="-j1"` it fails for me at the same point.

Try to change your `MAKEOPTS` to `MAKEOPTS="-j2"` and tell me if it makes any difference.

I will further investigate this because right now I don't know who is to blame for this.

**Comment by Moiman** [comment]
It works with MAKEOPTS="-j2".

**Comment by Ofekmeister** [comment]
This worked for me too.

I had an unrelated question 4re; did you find a solution to https://github.com/Khanattila/KNLMeansCL/issues/8 ? I think it may be useful for this Nvidia GT/GTX 500 series issue:

https://github.com/Khanattila/KNLMeansCL/issues/14
https://github.com/Khanattila/KNLMeansCL/issues/13

**Comment by 4re** [comment]
Issue 8 is not related to issues 13 and 14 as far as I can tell.

Issue 8 just means the headers included with the driver are too old, 13 and 14 are because political reasons I may suspect: nvidia wants to sell new hardware and does not give complete support to the old one, so the driver does not support opencl 1.2.

If nvidia does not support opencl 1.2 in GF 5XX series and below nobody can be anything about it, you are stuck with knlmeanscl 0.6.11 until you upgrade your hardware.

**Comment by 4re** [comment]
@Moiman, is this bug still affecting you? I'm no longer able to reproduce it.

**Comment by Moiman** [comment]
both media-libs/vapoursynth-28-r3 and -9999 still fail to build with -j1

**Comment by 4re** [comment]
What about r4? Does it fix it?

**Comment by Moiman** [comment]
r4 works.

**Comment by 4re** [comment]
NIce. :)
