### ISSUE TITLE
Blocked packages with @vapoursynth-plugins

### ISSUE THREAD

**Issue by Moiman** [4re/vapoursynth-portage#35]
These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild  N     ] media-plugins/vapoursynth-sangnom-2016.08.05::vapoursynth  USE="-doc" CPU_FLAGS_X86="sse4_1" 0 KiB
[blocks B      ] media-plugins/vapoursynth-sangnom ("media-plugins/vapoursynth-sangnom" is blocking media-plugins/vapoursynth-sangnommod-0.1.20150109)
[blocks B      ] media-plugins/vapoursynth-sangnommod ("media-plugins/vapoursynth-sangnommod" is blocking media-plugins/vapoursynth-sangnom-2016.08.05)

Total: 1 package (1 new), Size of downloads: 0 KiB
Conflict: 2 blocks (2 unsatisfied)

 * Error: The above package list contains packages which cannot be
 * installed at the same time on the same system.

  (media-plugins/vapoursynth-sangnom-2016.08.05:0/0::vapoursynth, ebuild scheduled for merge) pulled in by
    media-plugins/vapoursynth-sangnom required by @vapoursynth-plugins

  (media-plugins/vapoursynth-sangnommod-0.1.20150109:0/0::vapoursynth, installed) pulled in by
    media-plugins/vapoursynth-sangnommod required by @vapoursynth-plugins
    media-plugins/vapoursynth-sangnommod required by (media-plugins/vapoursynth-havsfunc-23:0/0::vapoursynth, installed)
    media-plugins/vapoursynth-sangnommod required by (media-plugins/vapoursynth-vstaambk-0.4.1:0/0::vapoursynth, installed)

For more information about Blocked Packages, please refer to the following
section of the Gentoo Linux x86 Handbook (architecture is irrelevant):

https://wiki.gentoo.org/wiki/Handbook:X86/Working/Portage#Blocked_packages

**Comment by 4re** [comment]
Yeah, that was the intended behaviour, both packages are incompatible with each other, and you are forced to uninstall sangnommod ir you want to install the new one (in theory, portage should take care of that by itself, but usually is in user hands because it can't decide by himself if you really want to uninstall the already installed package).

Anyway, I got ride of sangnommod altogether because is inferior in every way to the new port. After you resync again the overlay you will be left only with the new sangnom.

If for some unknown reason you want the old one, you would have to maintain it in your local overlay, but don't forget it can't coexist with the new one.

**Comment by 4re** [comment]
Mmh... sorry, I misunderstood you (I'm not really focused lately...), anyway, that problem is solved right now. Sorry for the mess.
