### ISSUE TITLE
Add vapoursynth-misc

### ISSUE THREAD

**Issue by Kagami** [4re/vapoursynth-portage#41]
Recent plugin by Myrsloik: http://forum.doom9.org/showthread.php?t=173871
Only 3 rather simple functions and no repository/build system.

Probably not that useful right now, creating issue here just to make this overlay as comprehensive as possible.

**Comment by 4re** [comment]
I didn't add it because that was supposed to be something to play around... I guess.

But because you requested it I will add an ebuild for it (and a modified source file because it does not compile out of  the box with GCC), so Gentoo folks can play around with it with minimal effort.

Not going to add it to sets/meta-package though.

**Comment by 4re** [comment]
Done via cd0b902647a0c960f3864a6882a2aba30e5e3109
