### ISSUE TITLE
media-video/mpv: live ebuild requires some fixes

### ISSUE THREAD

**Issue by Kagami** [4re/vapoursynth-portage#66]
0.23.0 patch can't be applied and there is no vaapi-hwaccel/vdpau-hwaccel flags anymore. Here is what I'm using right now, just as example:

```patch
--- /var/lib/layman/vapoursynth/media-video/mpv/mpv-9999-r9.ebuild	2017-11-01 01:05:43.776627567 +0300
+++ /usr/local/portage/media-video/mpv/mpv-9999-r9.ebuild	2017-11-01 01:21:09.501727211 +0300
@@ -139,11 +139,6 @@
 	tools? ( ${PYTHON_DEPS} )
 "
 
-PATCHES=(
-	"${FILESDIR}/${PN}-0.19.0-make-ffmpeg-version-check-non-fatal.patch"
-	"${FILESDIR}/${PN}-0.23.0-make-libavdevice-check-accept-libav.patch"
-)
-
 pkg_setup() {
 	[[ ${MERGE_TYPE} != "binary" ]] && python_setup
 }
@@ -248,8 +243,6 @@
 
 		# HWaccels:
 		# Automagic Video Toolbox HW acceleration. See Gentoo bug 577332.
-		$(use_enable vaapi vaapi-hwaccel)
-		$(use_enable vdpau vdpau-hwaccel)
 		$(use_enable cuda cuda-hwaccel)
 
 		# TV features:
```

**Comment by 4re** [comment]
Right now not even this works, they are enforcing a version number higher than the one in ffmpeg's current git.

Maybe the best will be to provide an ebuild with the last working git commit and go with it.

I'm done with this mpv drama.

Ofc, if somebody wants to maintain and keep mpv's live ebuild working, I'm willing to give them push access to this repo.

**Comment by Kagami** [comment]
It's possible to add `ffmpeg_LIVE_REPO="https://github.com/mpv-player/ffmpeg-mpv.git"` to `/etc/portage/env/media-video/ffmpeg` to use forked ffmpeg.

**Comment by 4re** [comment]
OK, changes made, let the decision of using mpv's fork to users discretion.

**Comment by Kagami** [comment]
Thanks.

**Comment by olifre** [comment]
@4re mpv has finally taken a step closer to the right direction again. 
There's now:
https://github.com/mpv-player/mpv/commit/a7a1ae0b3d60cdaab0774fcb08de33fa6b12848b
which adds the flag:
`--enable-ffmpeg-garbage`
which has in a later commit been renamed to the less harsh:
`--enable-ffmpeg-upstream`.
Maybe it would be best to add a flag `system-ffmpeg` to the live ebuild (maybe on by default? depends on future developments) which sets that flag. 
It's not yet sufficient to make things actually build, though:
https://github.com/mpv-player/mpv/issues/5066
but I hope that, now that the first rage is over, things will turn out for good and using system-ffmpeg will mostly work. 

What do you think?

**Comment by olifre** [comment]
Note: related work is also here: 
https://bugs.gentoo.org/635650
Maybe it's even better (or at least easier) to wait for the main portage tree to take a decision.

**Comment by olifre** [comment]
@4re I fully agree on all points. There's no real gain from entering a political discussion, the positions of the involved parties will not really change in any case. The only outcome of such political arguments, as usual, is pain for distros and users. 

The thing we could easily do would be to add the `--enable-ffmpeg-upstream` flag. This change has pretty recently gone into portage main:
https://github.com/gentoo/gentoo/pull/6105
As it stands now, this allows to compile `mpv-9999` against `ffmpeg-9999` again, and it's less of a hack than setting `-DLIBAVCODEC_MPV=1`. I'm not sure about the exact feature / bug implications, especially since the `ffmpeg-mpv` fork has the patches scattered in the history (instead of piled up at the end of the history), so it's hard to compare against `ffmpeg`, and even harder to deduce what the causes of missing those patches will be. 

So mainly, my suggestion would be a "re-sync" with portage main ;-). 

The other idea (packaging `ffmpeg-mpv` and making `mpv` work with that if `system-ffmpeg` is not set) would indeed induce a lot of work - right now, I also don't feel up for it. Since people have asked on the Gentoo bugtracker and the PR to portage I linked just here, I would again go the easy way and just wait for a decision by the main tree. 

Does this sound sensible?

**Comment by 4re** [comment]
ILGTM. Merged.

**Comment by olifre** [comment]
@4re Just to take note, finally:
https://github.com/mpv-player/mpv/commit/f19797dea62ab9619a18a2ffab1b67bdafe55b8c
ffmpeg-mpv is gone (at least for now), and upstream ffmpeg is supported "officially" again(!). 

There's also https://github.com/ffmpv/ffmpv now, but I don't know any details (doesn't look like a lot of development is going on there). 

This also means we could drop ` --enable-ffmpeg-upstream.` for good again, but maybe it's easier to wait for the main portage tree to take action and just re-sync. https://bugs.gentoo.org/show_bug.cgi?id=635650 has become pretty active again now.

**Comment by 4re** [comment]
This is really nice to know. As soon as I get home I will take a look at it.

I guess if `--enable-ffmpeg-upstream` option does not break compilation at configure time we can wait, if it does, it would be nicer to at least make the live ebuild work until Gentoo makes its changes and sync.

**Comment by olifre** [comment]
> I guess if --enable-ffmpeg-upstream option does not break compilation at configure time we can wait, if it does, it would be nicer to at least make the live ebuild work until Gentoo makes its changes and sync.

Indeed, it breaks for the moment (I checked just now) :-(. So the flag needs to be removed again, portage now appears to wait a bit, maybe they're unsure how stable the situation is. 

If we're lucky, this might also mean we could drop the dependency on `=ffmpeg-9999` at some point and use some modern release again. 

The only ugly news is that it seems all this has only happened after the project leader and founder of mpv stepped down, he is now even contributing via pull requests and has revoked his own push permissions. I don't know any details (even though I am in the mpv organization), but I surely hope it will not adversely affect mpv development in the future. He has also withdrawn as ffmpeg developer as far as I know.
